# Generated by Django 2.2.5 on 2019-10-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contact_info',
            field=models.CharField(max_length=100),
        ),
    ]
